import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="relative grid grid-cols-2 h-[110vh]">
        <div className="mt-[140px] ml-[120px] col-span-1">
          <p className="font-montserrat text-text/50 text-[22px]">
            Sua casa com as
          </p>
          <h1 className="mb-6 font-black text-[82px] text-text font-sans leading-[94px]">
            melhores plantas
          </h1>
          <p className="font-normal font-montserrat text-text/50 leading-[26px] pr-6">
            Encontre aqui uma vasta seleção de plantas para decorar a sua casa e
            torná-lo uma pessoa mais feliz no seu dia a dia. Entre com seu
            e-mail e assine nossa newsletter para saber das novidades da marca.
          </p>
          <div className='flex items-center'>
            <input type="email" placeholder="Insira seu e-mail" />
            <button>Assinar newsletter</button>
          </div>
        </div>

        <div className="col-span-1">
          <div className='absolute -top-20 -right-20 bg-[url("/assets/vector/paint.svg")] w-[850px] h-[1150px] 2xl:w-[1009px] 2xl:h-[1087px] bg-no-repeat -z-20 bg-contain' />
          <div className='absolute -top-24 right-48 bg-[url("/assets/images/heroImage.png")] w-[787px] h-[1183px] bg-no-repeat -z-10 bg-contain' />
        </div>
      </section>
    </div>
  )
}
