import Head from 'next/head'

import { HiOutlineMail } from 'react-icons/hi'
import { FiMousePointer } from 'react-icons/fi'
import { FiShoppingCart } from 'react-icons/fi'
import { FiTruck } from 'react-icons/fi'

import SaleCard from '../components/SaleCard'
import { products, videos } from '../data'
import VideoCard from '../components/VideoCard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="relative md:grid-cols-2 md:grid h-[100vh] md:h-[880px]">
          <div className="md:mt-[80px] 2xl:ml-[358px] mt-[34px] ml-4 md:ml-[100px] col-span-1">
            <p className="font-montserrat text-text/50 text-[22px]">
              Sua casa com as
            </p>
            <h1 className="mb-6 font-black text-[32px] md:text-[82px] text-text font-sans leading-[36px] md:leading-[94px]">
              melhores plantas
            </h1>
            <p className="w-[200px] md:w-auto font-normal font-montserrat text-text/50 leading-[26px] pr-6">
              Encontre aqui uma vasta seleção de plantas para decorar a sua casa
              e torná-lo uma pessoa mais feliz no seu dia a dia. Entre com seu
              e-mail e assine nossa newsletter para saber das novidades da
              marca.
            </p>
            <div className="relative items-center block md:bg-white md:flex font-montserrat shadow-custom-shadow mt-9">
              <HiOutlineMail
                size={24}
                className="absolute top-7 md:top-1/3 left-5 text-text/50"
              />
              <input
                type="email"
                placeholder="Insira seu e-mail"
                className="mb-4 md:mb-0 w-[95%] m-auto md:w-[65%] text-text/50 py-7 pl-14 focus:outline-none"
              />
              <button className="px-5 w-[95%] md:w-[35%] font-bold text-center text-white bg-yellow py-7">
                Assinar newsletter
              </button>
            </div>
          </div>
          <div className="col-span-1">
            <div className="absolute -top-5 md:-top-20 right-[-720px] 2xl:-right-16 md:-right-28 bg-[url('/assets/vector/paint.svg')] w-[850px] h-[1150px] 2xl:w-[1009px] 2xl:h-[1087px] bg-no-repeat -z-20 bg-contain" />
            <div>
              <div className="absolute right-0 top-36 md:-top-24 2xl:right-[400px] md:right-32 bg-[url('/assets/images/heroImage.png')] w-[226px] md:w-[787px] h-[340px] md:h-[1000px] 2xl:h-[1183px] bg-no-repeat -z-10 bg-contain" />
            </div>
          </div>
        </section>

        <section className="w-[95vw] -mt-16 md:w-auto 2xl:w-[995px] m-auto md:mx-[200px] 2xl:m-auto shadow-custom-shadow">
          <div className="grid grid-cols-5">
            <div className="hidden md:block col-span-3 bg-[url('/assets/images/myPlant.png')] bg-cover bg-no-repeat h-[440px]"></div>
            <div className="col-span-5 bg-white md:col-span-2">
              <div className="pt-[58px] pl-[24px] md:block">
                <span className="text-[22px] text-text/50 font-montserrat block">
                  Como conseguir
                </span>
                <strong className="text-text text-[42px] font-black mb-[32px] mt-[12px] block">
                  minha planta
                </strong>
                <ul className="flex flex-col gap-8 font-montserrat text-text/50 ">
                  <li className="text-[22px] flex items-center gap-4">
                    <span className="inline-block p-3 rounded-full bg-yellow">
                      <FiMousePointer size={18} className="text-white" />
                    </span>
                    Escolha suas plantas
                  </li>
                  <li className="text-[22px] flex items-center gap-4">
                    <span className="inline-block p-3 rounded-full bg-yellow">
                      <FiShoppingCart size={18} className="text-white" />
                    </span>
                    Faça seu pedido
                  </li>
                  <li className="text-[22px] flex items-center gap-4">
                    <span className="inline-block p-3 rounded-full bg-yellow">
                      <FiTruck size={18} className="text-white" />
                    </span>
                    Aguarde na sua casa
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-[44px] mx-auto md:block md:mx-[100px]">
          <div className="text-center">
            <span className="font-montserrat text-text/50 text-[22px]">
              Conheça nossas
            </span>
            <h3 className="font-black text-[82px] text-text">ofertas</h3>
          </div>
          <div className="md:grid grid-cols-3 grid-rows-2 flex flex-col items-center gap-4  md:gap-[30px] m-auto max-w-[1166px]">
            {products.map((product) => (
              <SaleCard
                key={product.id}
                title={product.title}
                img={product.img}
                price={product.price}
              />
            ))}
          </div>
        </section>

        <section className="hidden pt-[108px] md:flex 2xl:grid grid-cols-2">
          <div className="min-w-[668px] 2xl:w-[850px] block 2xl:col-span-1">
            <div className="w-[500px] h-[480px] 2xl:w-[638px] 2xl:h-[580px] bg-yellow relative drop-shadow-xl">
              <div className="drop-shadow-xl bg-[url('/assets/images/client1.png')] w-[381px] 2xl:w-[481px] h-[445px] 2xl:h-[562px] bg-contain bg-no-repeat absolute top-[99px] -right-1/3" />
            </div>
          </div>

          <div className="md:mt-[88px] 2xl:mt-[160px] 2xl:col-span-1">
            <h4 className="font-black text-[38px] ml-[32px] 2xl:ml-0">
              Não acredite em nós <br /> veja o que os clientes tem a dizer
            </h4>
            <div className="w-[585px] mx-auto 2xl:mx-0 font-montserrat text-text/50 flex">
              <div className="w-[100px]">
                <div className="bg-yellow p-5 w-[72px] h-[72px] rounded-full relative mt-9 mr-[30px] block">
                  <span className="bg-[url('/assets/vector/quote.svg')] absolute top-[30%] left-[17%] block w-[46px] h-[28px] bg-contain bg-no-repeat" />
                </div>
              </div>
              <div className="mt-9">
                <p className="md:pb-4 2xl:pb-8">
                  Nullam a orci vitae orci fringilla pulvinar sit amet quis
                  felis. Quisque vel ornare arcu. Fusce urna quam, tempus vitae
                  vehicula et, efficitur non sem. Morbi tincidunt congue lorem
                  eu tempor. Nulla bibendum ligula lorem, vel sollicitudin nibh
                  scelerisque non. Proin ut nisi congue, sodales tellus at,
                  consectetur tellus. Praesent ac elit quis purus congue
                  bibendum. Etiam nec massa ac enim vehicula maximus.
                  Pellentesque semper fermentum maximus. Integer dignissim
                  libero felis, id tempor purus viverra non. Quisque sodales non
                  lacus ut tincidunt. Cras in venenatis leo.”
                </p>
                <div className="flex flex-col items-start gap-1">
                  <span className="text-text">Juliana Ferraz</span>
                  <span>Cliente desde 2018</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-[108px] mx-auto md:block md:mx-[100px]">
          <div className="text-center">
            <span className="font-montserrat text-text/50 text-[22px]">
              Veja aqui os nossos
            </span>
            <h3 className="font-black text-[32px] md:text-[82px] text-text">vídeos</h3>
          </div>
          <div className="w-[80%] items-center mx-auto flex-col md:flex-row flex justify-between gap-[30px] md:w-[1166px] md:mx-auto">
            {videos.map((video) => (
              <VideoCard
                key={video.id}
                img={video.img}
                title={video.title}
                date={video.date}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}
